# Generated by Django 3.2.3 on 2021-06-30 17:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=main.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_skills', models.CharField(max_length=1000)),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ski_id', to='main.resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_id', to='main.resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience_time', models.DecimalField(decimal_places=1, default=None, max_digits=2)),
                ('designition', models.CharField(max_length=500)),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_id', to='main.resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=250)),
                ('institute', models.CharField(max_length=500)),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_id', to='main.resumes')),
            ],
        ),
        migrations.CreateModel(
            name='classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_computer_sience', models.BooleanField()),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_id', to='main.resumes')),
            ],
        ),
    ]
