# Generated by Django 3.2.3 on 2021-07-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_experience_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_time',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
