# Generated by Django 3.2.3 on 2021-07-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_experience_experience_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumes',
            name='contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
